# Generated by Django 3.1.6 on 2021-03-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_custamor',
            new_name='is_customer',
        ),
    ]
